import calendar

a = calendar.calendar(2020)
print(a)
print()
b = calendar.weekheader(3)
print(b)
print()
print(calendar.firstweekday())
print()
print(calendar.month(2020,9))
print()
print(calendar.monthcalendar(2019,3))
print()
print(calendar.weekday(2020,9,15))
print()
print(calendar.isleap(2020))
print()
print(calendar.leapdays(2001,2020))
